name: Run
on:
  workflow_dispatch:
    inputs:
      message:
        description: ECS cluster
        type: string
        default: "hello world"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: echo "VAR1=echo \"${{ inputs.message }}\"" >> $GITHUB_ENV
      - name: Run
        run: ${{ env.VAR1 }}
