name: Run
on:
  workflow_dispatch:
    inputs:
      message:
        description: ECS cluster
        type: string
        default: "hello world"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          msg="echo \"${{ inputs.message }}\""
          echo "::add-mask::$msg"
          echo "VAR1=$msg" >> $GITHUB_ENV
      - name: Run
        run: ${{ env.VAR1 }}
